# configs/brand_model_types.py

brand_model_types = {
    "Supermicro": {
        "X10": "Computer Servers",
        "X11": "Computer Servers",
        "X12": "Computer Servers",
        "X13": "Computer Servers",
        "SuperServer": "Computer Servers",
        "A2": "Computer Servers",
        "A3": "Computer Servers",
        "H11": "Computer Servers",
        "H12": "Computer Servers",
        "H13": "Computer Servers",
        "BigTwin": "Computer Servers",
        "FatTwin": "Computer Servers",
        "SuperBlade": "Computer Servers",
        "MicroCloud": "Computer Servers",
    },
    "Lenovo": {
        "ThinkBook": "PC Laptops & Netbooks",
        "ThinkPad": "PC Laptops & Netbooks",
        "IdeaPad": "PC Laptops & Netbooks",
        "Yoga": "PC Laptops & Netbooks",
        "ThinkCentre": "PC Desktops & All-In-Ones",
        "ThinkStation": "PC Desktops & All-In-Ones",
        "ThinkServer": "Computer Servers",
        "System X": "Computer Servers",
        "Legion": "PC Laptops & Netbooks",
        "IdeaCentre": "PC Desktops & All-In-Ones",
    },
    "Dell": {
        "Latitude": "PC Laptops & Netbooks",
        "XPS": {
            "PC Laptops & Netbooks": ["laptop", "ultrabook", "2-in-1", "13", "15", "17"],
            "PC Desktops & All-In-Ones": ["desktop", "tower", "all-in-one", "aio", "8000", "8100", "8200", "8300", "8400", "8500", "8700", "8900", "8910", "8920", "8930", "8940", "8950"]
        },
        "Inspiron": {
            "PC Laptops & Netbooks": ["laptop", "notebook", "2-in-1", "convertible"],
            "PC Desktops & All-In-Ones": ["desktop", "tower", "all-in-one", "aio"]
        },
        "Vostro": {
            "PC Laptops & Netbooks": ["laptop", "notebook"],
            "PC Desktops & All-In-Ones": ["desktop", "tower", "small form factor", "sff"]
        },
        "Precision": {
            "PC Laptops & Netbooks": ["mobile", "laptop", "notebook", "7710", "7720", "7730", "7740", "7750", "7760", "7770", "7780", "7790", "5510", "5520", "5530", "5540", "5550", "5560", "5570", "5580", "5590", "5591", "5750", "5760", "5770", "3510", "3520", "3530", "3540", "3541", "3550", "3551", "3560", "3561", "3570", "3571", "3580", "3581", "3590", "3591"],
            "PC Desktops & All-In-Ones": ["tower", "desktop", "sff", "workstation", "small form factor", "fixed", "rack", "t3", "t5", "t7", "3420", "3430", "3431", "3440", "3460", "3630", "3631", "3640", "3650", "3660", "3680", "5810", "5820", "5860", "7820", "7875", "7920", "7960", "3450"]
        },
        "OptiPlex": "PC Desktops & All-In-Ones",
        "Optiplex": "PC Desktops & All-In-Ones",
        "PowerEdge": "Computer Servers",
        "PowerConnect": "Network Switches",
        "Force10": "Network Switches",
        "S-Series": "Network Switches",
        "N-Series": "Network Switches",
        "Compellent": "SAN Disk Arrays",
        "EqualLogic": "SAN Disk Arrays",
        "PowerVault": "SAN Disk Arrays",
        "SC": "SAN Disk Arrays",
        "PS": "SAN Disk Arrays",
        "UltraSharp": "Monitors",
        "UP": "Monitors",
        "P": "Monitors",
        "S": "Monitors",
        "Alienware": {
            "PC Laptops & Netbooks": ["laptop", "notebook", "m15", "m17", "x14", "x15", "x17", "area-51m"],
            "PC Desktops & All-In-Ones": ["aurora", "desktop", "tower", "area 51", "area-51"]
        },
        "G Series": "PC Laptops & Netbooks",
    },
    "HP": {
        "EliteBook": "PC Laptops & Netbooks",
        "ProBook": "PC Laptops & Netbooks",
        "Envy": "PC Laptops & Netbooks",
        "Spectre": "PC Laptops & Netbooks",
        "ZBook": "PC Laptops & Netbooks",
        "EliteDesk": "PC Desktops & All-In-Ones",
        "ProDesk": "PC Desktops & All-In-Ones",
        "Z Workstation": "PC Desktops & All-In-Ones",
        "Z420": "PC Desktops & All-In-Ones",
        "Z440": "PC Desktops & All-In-Ones",
        "Z620": "PC Desktops & All-In-Ones",
        "Z640": "PC Desktops & All-In-Ones",
        "Z820": "PC Desktops & All-In-Ones",
        "Z840": "PC Desktops & All-In-Ones",
        "Z1": "PC Desktops & All-In-Ones",
        "Z2": "PC Desktops & All-In-Ones",
        "Z4": "PC Desktops & All-In-Ones",
        "Z6": "PC Desktops & All-In-Ones",
        "Z8": "PC Desktops & All-In-Ones",
        "ProLiant": "Computer Servers",
        "Pavilion": {
            "PC Laptops & Netbooks": ["laptop", "notebook"],
            "PC Desktops & All-In-Ones": ["desktop", "tower", "all-in-one"]
        },
        "Omen": "PC Laptops & Netbooks",
        "Compaq": "PC Laptops & Netbooks",
        "3PAR": "SAN Disk Arrays",
        "EVA": "SAN Disk Arrays",
        "MSA": "SAN Disk Arrays",
        "P2000": "SAN Disk Arrays",
        "P4000": "SAN Disk Arrays",
        "LeftHand": "SAN Disk Arrays",
        "t430": "Servers, Clients & Terminals",
        "t530": "Servers, Clients & Terminals",
        "t630": "Servers, Clients & Terminals",
        "t640": "Servers, Clients & Terminals",
        "t730": "Servers, Clients & Terminals",
        "t740": "Servers, Clients & Terminals",
        "mt21": "Servers, Clients & Terminals",
        "mt22": "Servers, Clients & Terminals",
        "mt440": "Servers, Clients & Terminals",
        "mt645": "Servers, Clients & Terminals",
    },
    "HPE": {
        "ProLiant": "Computer Servers",
        "ProCurve": "Network Switches",
        "Aruba": "Wireless Access Points",
        "OfficeConnect": "Network Switches",
        "3PAR": "SAN Disk Arrays",
        "Primera": "SAN Disk Arrays",
        "Nimble": "SAN Disk Arrays",
        "MSA": "SAN Disk Arrays",
        "StoreEasy": "NAS Disk Arrays",
    },
    #do not EVER rename "Desktops & All-In-Ones" to "Desktops & All-In-One Computers" as that is WRONG.
    "Apple": {
        "MacBook": "Apple Laptops",
        "Macbook": "Apple Laptops",
        "MacBook Air": {
            "Apple Laptops": ["M1", "M2", "M3", "M4 13-inch", "M4 15-inch", "13-inch Early 2024", "15-inch Mid 2024"]
        },
        "MacBook Pro": {
            "Apple Laptops": ["M1 13-inch", "M2 13-inch", "M3 14-inch", "M3 16-inch", "M4 14-inch", "M4 16-inch", "14-inch Late 2023", "16-inch Late 2023"]
        },
        "iMac": "Apple Desktops & All-In-Ones",
        "Mac mini": "Apple Desktops & All-In-Ones",
        "Mac Mini": "Apple Desktops & All-In-Ones",
        "Mac Pro": "Apple Desktops & All-In-Ones",
        "Mac Studio": "Apple Desktops & All-In-Ones",
        "XServe": "Computer Servers",
        "XServe": "Computer Servers",
        "iPhone": "Cell Phones & Smartphones",
        "iPad": "Tablets & eReaders",
    },
    "Microsoft": {
        "Surface": {
            "PC Laptops & Netbooks": ["laptop", "book"],
            "Tablets & eReaders": ["tablet", "go", "rt", "pro"]
        },
    },
    "Samsung": {
        "Galaxy": "Cell Phones & Smartphones",
        "ViewFinity": "Monitors",
        "Odyssey": "Monitors", 
        "Smart Monitor": "Monitors",
        "CRG": "Monitors",
        "CHG": "Monitors",
        "CFG": "Monitors",
        "C24": "Monitors",
        "C27": "Monitors", 
        "C32": "Monitors",
        "C34": "Monitors",
        "C49": "Monitors",
        "U28": "Monitors",
        "U32": "Monitors",
        "UR": "Monitors",
        "UE": "Monitors",
    },
    "Google": {
        "Pixel": "Cell Phones & Smartphones",
    },
    "OnePlus": {
        "OnePlus": "Cell Phones & Smartphones",
        "Nord": "Cell Phones & Smartphones",
    },
    "Acer": {
        "Swift": "PC Laptops & Netbooks",
        "Chromebook": "PC Laptops & Netbooks",
        "Aspire": "PC Laptops & Netbooks",
        "Predator": "PC Laptops & Netbooks",
        "Nitro": "PC Laptops & Netbooks",
        "TravelMate": "PC Laptops & Netbooks",
        "Spin": "PC Laptops & Netbooks",
    },
    "Asus": {
        "ZenBook": "PC Laptops & Netbooks",
        "VivoBook": "PC Laptops & Netbooks",
        "Chromebook": "PC Laptops & Netbooks",
        "ROG": "PC Laptops & Netbooks",
        "TUF": "PC Laptops & Netbooks",
        "ExpertBook": "PC Laptops & Netbooks",
        "Strix": "Graphics/Video Cards",
        "TUF Gaming": "Graphics/Video Cards",
        "Dual": "Graphics/Video Cards",
        "Phoenix": "Graphics/Video Cards",
        "Turbo": "Graphics/Video Cards",
    },
    "ASUS": {
        "ZenBook": "PC Laptops & Netbooks",
        "VivoBook": "PC Laptops & Netbooks",
        "Chromebook": "PC Laptops & Netbooks",
        "ROG": "PC Laptops & Netbooks",
        "TUF": "PC Laptops & Netbooks",
        "ExpertBook": "PC Laptops & Netbooks",
        "Strix": "Graphics/Video Cards",
        "TUF Gaming": "Graphics/Video Cards",
        "Dual": "Graphics/Video Cards",
        "Phoenix": "Graphics/Video Cards",
        "Turbo": "Graphics/Video Cards",
    },
    "Toshiba": {
        "Satellite": "PC Laptops & Netbooks",
        "Portege": "PC Laptops & Netbooks",
        "Tecra": "PC Laptops & Netbooks",
        "Dynabook": "PC Laptops & Netbooks",
    },
    "LG": {
        "Gram": "PC Laptops & Netbooks",
        "Ultra": "PC Laptops & Netbooks",
    },
    "MSI": {
        "GS": "PC Laptops & Netbooks",
        "GE": "PC Laptops & Netbooks",
        "GL": "PC Laptops & Netbooks",
        "GP": "PC Laptops & Netbooks",
        "GT": "PC Laptops & Netbooks",
        "Prestige": "PC Laptops & Netbooks",
        "Modern": "PC Laptops & Netbooks",
        "Alpha": "PC Laptops & Netbooks",
        "Creator": "PC Laptops & Netbooks",
        "Stealth": "PC Laptops & Netbooks",
        "Pulse": "PC Laptops & Netbooks",
        "Katana": "PC Laptops & Netbooks",
        "Sword": "PC Laptops & Netbooks",
        "Aegis": "PC Desktops & All-In-Ones",
        "Trident": "PC Desktops & All-In-Ones",
        "Infinite": "PC Desktops & All-In-Ones",
        "Gaming": "Graphics/Video Cards",
        "Ventus": "Graphics/Video Cards",
        "Suprim": "Graphics/Video Cards",
        "Gaming X": "Graphics/Video Cards",
        "Gaming Z": "Graphics/Video Cards",
        "Sea Hawk": "Graphics/Video Cards",
        "Armor": "Graphics/Video Cards",
    },
    "Razer": {
        "Blade": "PC Laptops & Netbooks",
        "Book": "PC Laptops & Netbooks",
    },
    "Alienware": {
        "Area-51m": "PC Laptops & Netbooks",
        "Area-51": "PC Desktops & All-In-Ones",
        "Area 51": "PC Desktops & All-In-Ones",
        "Aurora": "PC Desktops & All-In-Ones",
        "m15": "PC Laptops & Netbooks",
        "m17": "PC Laptops & Netbooks",
        "m18": "PC Laptops & Netbooks",
        "x14": "PC Laptops & Netbooks",
        "x15": "PC Laptops & Netbooks",
        "x16": "PC Laptops & Netbooks",
        "x17": "PC Laptops & Netbooks",
    },
    "IBM": {
        "ThinkPad": "PC Laptops & Netbooks",
        "XIV": "SAN Disk Arrays",
        "DS8000": "SAN Disk Arrays",
        "FlashSystem": "SAN Disk Arrays",
        "Storwize": "SAN Disk Arrays",
        "SVC": "SAN Disk Arrays",
    },
    "Gateway": {
        "NV": "PC Laptops & Netbooks",
        "NE": "PC Laptops & Netbooks",
    },
    "Compaq": {
        "Presario": "PC Laptops & Netbooks",
    },
    "Fujitsu": {
        "Lifebook": "PC Laptops & Netbooks",
        "Esprimo": "PC Desktops & All-In-Ones",
    },
    "Panasonic": {
        "Toughbook": "PC Laptops & Netbooks",
        "Let's Note": "PC Laptops & Netbooks",
    },
    "Cisco": {
        "UCS": "Computer Servers",
        "C220": "Computer Servers",
        "C240": "Computer Servers",
        "C480": "Computer Servers",
        "C260": "Computer Servers",
        "B200": "Computer Servers",
        "B420": "Computer Servers",
        "APIC": "Computer Servers",
        "Catalyst": "Network Switches",
        "Nexus": "Network Switches",
        "WS-C": "Network Switches",
        "ISR": "Enterprise Routers",
        "ASR": "Enterprise Routers",
        "Meraki": "Network Switches",
        "AIR": "Wireless Access Points",
        "Aironet": "Wireless Access Points",
    },
    "Juniper": {
        "EX": "Network Switches",
        "SRX": "Firewall & VPN Devices",
        "MX": "Enterprise Routers",
        "QFX": "Network Switches",
        "PTX": "Enterprise Routers",
    },
    "Aruba": {
        "IAP": "Wireless Access Points",
        "Instant": "Wireless Access Points",
        "6000": "Network Switches",
        "3000": "Network Switches",
        "2000": "Network Switches",
    },
    "Ubiquiti": {
        "UniFi": "Network Switches",
        "EdgeRouter": "Enterprise Routers",
        "EdgeSwitch": "Network Switches",
        "UAP": "Wireless Access Points",
        "Dream Machine": "Enterprise Routers",
    },
    "Netgear": {
        "ProSAFE": "Network Switches",
        "ReadyNAS": "NAS Disk Arrays",
        "Nighthawk": "Enterprise Routers",
    },
    "D-Link": {
        "DGS": "Network Switches",
        "DES": "Network Switches",
    },
    "TP-Link": {
        "TL-": "Network Switches",
        "Archer": "Enterprise Routers",
        "Omada": "Network Switches",
    },
    "Brocade": {
        "ICX": "Network Switches",
        "VDX": "Network Switches",
    },
    "Fortinet": {
        "FortiGate": "Firewall & VPN Devices",
        "FortiSwitch": "Network Switches",
    },
    "Ruckus": {
        "ICX": "Network Switches",
        "ZoneFlex": "Wireless Access Points",
    },
    "NetApp": {
        "FAS": "SAN Disk Arrays",
        "AFF": "SAN Disk Arrays",
        "NAJ": "SAN Disk Arrays",
        "DS": "SAN Disk Arrays",
        "DS24": "SAN Disk Arrays",
        "DS2246": "SAN Disk Arrays",
        "DS4246": "SAN Disk Arrays",
        "DS4486": "SAN Disk Arrays",
        "E-Series": "SAN Disk Arrays",
        "EF": "SAN Disk Arrays",
        "FX": "SAN Disk Arrays",
        "C190": "SAN Disk Arrays",
        "A200": "SAN Disk Arrays",
        "A250": "SAN Disk Arrays",
        "A400": "SAN Disk Arrays",
        "A700": "SAN Disk Arrays",
        "A800": "SAN Disk Arrays",
    },
    "EMC": {
        "VNX": "SAN Disk Arrays",
        "VMAX": "SAN Disk Arrays",
        "PowerMax": "SAN Disk Arrays",
        "Unity": "SAN Disk Arrays",
        "XtremIO": "SAN Disk Arrays",
        "Isilon": "NAS Disk Arrays",
        "Celerra": "NAS Disk Arrays",
        "VNXe": "SAN Disk Arrays",
        "CX": "SAN Disk Arrays",
        "AX": "SAN Disk Arrays",
    },
    "Pure Storage": {
        "FlashArray": "SAN Disk Arrays",
        "FlashBlade": "SAN Disk Arrays",
        "FA": "SAN Disk Arrays",
        "FB": "SAN Disk Arrays",
    },
    "Hitachi": {
        "VSP": "SAN Disk Arrays",
        "HUS": "SAN Disk Arrays",
        "AMS": "SAN Disk Arrays",
        "TagmaStore": "SAN Disk Arrays",
        "Thunder": "SAN Disk Arrays",
    },
    "Quantum": {
        "StorNext": "SAN Disk Arrays",
        "Xcellis": "SAN Disk Arrays",
        "DXi": "SAN Disk Arrays",
    },
    "Synology": {
        "DiskStation": "NAS Disk Arrays",
        "RackStation": "NAS Disk Arrays",
        "DS": "NAS Disk Arrays",
        "RS": "NAS Disk Arrays",
    },
    "QNAP": {
        "TS": "NAS Disk Arrays",
        "TurboNAS": "NAS Disk Arrays",
    },
    "Drobo": {
        "B800": "NAS Disk Arrays",
        "5N": "NAS Disk Arrays",
        "5D": "NAS Disk Arrays",
    },
    "Promise": {
        "VTrak": "SAN Disk Arrays",
        "Vess": "SAN Disk Arrays",
    },
    "Infortrend": {
        "EonStor": "SAN Disk Arrays",
        "GS": "SAN Disk Arrays",
    },
    "EVGA": {
        "GeForce": "Graphics/Video Cards",
        "GTX": "Graphics/Video Cards",
        "RTX": "Graphics/Video Cards",
        "FTW": "Graphics/Video Cards",
        "SC": "Graphics/Video Cards",
        "XC": "Graphics/Video Cards",
        "SSC": "Graphics/Video Cards",
        "Hybrid": "Graphics/Video Cards",
        "KingPin": "Graphics/Video Cards",
        "Classified": "Graphics/Video Cards",
    },
    "GIGABYTE": {
        "Windforce": "Graphics/Video Cards",
        "Gaming OC": "Graphics/Video Cards",
        "Aorus": "Graphics/Video Cards",
        "Eagle": "Graphics/Video Cards",
        "Vision": "Graphics/Video Cards",
        "Turbo": "Graphics/Video Cards",
    },
    "ZOTAC": {
        "Gaming": "Graphics/Video Cards",
        "AMP": "Graphics/Video Cards",
        "Trinity": "Graphics/Video Cards",
        "Mini": "Graphics/Video Cards",
        "GeForce": "Graphics/Video Cards",
        "GTX": "Graphics/Video Cards",
        "RTX": "Graphics/Video Cards",
    },
    "Sapphire": {
        "Nitro": "Graphics/Video Cards",
        "Pulse": "Graphics/Video Cards",
        "Radeon": "Graphics/Video Cards",
        "Toxic": "Graphics/Video Cards",
        "Vapor-X": "Graphics/Video Cards",
    },
    "XFX": {
        "Radeon": "Graphics/Video Cards",
        "RX": "Graphics/Video Cards",
        "THICC": "Graphics/Video Cards",
        "Speedster": "Graphics/Video Cards",
        "MERC": "Graphics/Video Cards",
    },
    "PowerColor": {
        "Red Devil": "Graphics/Video Cards",
        "Red Dragon": "Graphics/Video Cards",
        "Hellhound": "Graphics/Video Cards",
        "Fighter": "Graphics/Video Cards",
        "Radeon": "Graphics/Video Cards",
    },
    "PNY": {
        "GeForce": "Graphics/Video Cards",
        "GTX": "Graphics/Video Cards",
        "RTX": "Graphics/Video Cards",
        "Quadro": "Graphics/Video Cards",
        "Verto": "Graphics/Video Cards",
        "XLR8": "Graphics/Video Cards",
    },
    "ASRock": {
        "Phantom Gaming": "Graphics/Video Cards",
        "Challenger": "Graphics/Video Cards",
        "Steel Legend": "Graphics/Video Cards",
        "Taichi": "Graphics/Video Cards",
    },
    "VisionTek": {
        "Radeon": "Graphics/Video Cards",
        "GeForce": "Graphics/Video Cards",
    },
    "Gainward": {
        "GeForce": "Graphics/Video Cards",
        "Phoenix": "Graphics/Video Cards",
        "Phantom": "Graphics/Video Cards",
    },
    "Palit": {
        "GeForce": "Graphics/Video Cards",
        "GameRock": "Graphics/Video Cards",
        "JetStream": "Graphics/Video Cards",
        "StormX": "Graphics/Video Cards",
    },
    "Inno3D": {
        "GeForce": "Graphics/Video Cards",
        "iChill": "Graphics/Video Cards",
        "Twin X2": "Graphics/Video Cards",
        "Compact": "Graphics/Video Cards",
    },
    "Colorful": {
        "iGame": "Graphics/Video Cards",
        "GeForce": "Graphics/Video Cards",
        "Battle Ax": "Graphics/Video Cards",
    },
    "KFA2": {
        "GeForce": "Graphics/Video Cards",
        "EX": "Graphics/Video Cards",
        "OC": "Graphics/Video Cards",
    },
    "Galax": {
        "GeForce": "Graphics/Video Cards",
        "EX": "Graphics/Video Cards",
        "OC": "Graphics/Video Cards",
    },
    "Yeston": {
        "GeForce": "Graphics/Video Cards",
        "Radeon": "Graphics/Video Cards",
        "Cute Pet": "Graphics/Video Cards",
    },
    "Biostar": {
        "GeForce": "Graphics/Video Cards",
        "Radeon": "Graphics/Video Cards",
    },
    "NVIDIA": {
        "GeForce": "Graphics/Video Cards",
        "GTX": "Graphics/Video Cards",
        "RTX": "Graphics/Video Cards",
        "Quadro": "Graphics/Video Cards",
        "Tesla": "Graphics/Video Cards",
        "Founders Edition": "Graphics/Video Cards",
        "Titan": "Graphics/Video Cards",
    },
    "AMD": {
        "Radeon": "Graphics/Video Cards",
        "RX": "Graphics/Video Cards",
        "R9": "Graphics/Video Cards",
        "R7": "Graphics/Video Cards",
        "R5": "Graphics/Video Cards",
        "FirePro": "Graphics/Video Cards",
        "Instinct": "Graphics/Video Cards",
    },
    "iKey": {
        "IK-": "Cases, Covers, Keyboard Folios",
        "Attachable": "Cases, Covers, Keyboard Folios",
        "Keyboard": "Cases, Covers, Keyboard Folios",
    },
    "Lexmark": {
        "50F0Z00": "Toner Cartridges",
        "Return Program": "Toner Cartridges",
        "Imaging Unit": "Toner Cartridges",
        "Imaging Drum": "Toner Cartridges",
        "Toner": "Toner Cartridges",
        "Cartridge": "Toner Cartridges",
    },
    # Most Popular Vintage Graphics Card Brands
    "3DFX": {
        "Voodoo": "Vintage Parts & Accessories",
        "Voodoo2": "Vintage Parts & Accessories", 
        "Voodoo3": "Vintage Parts & Accessories",
        "Voodoo4": "Vintage Parts & Accessories",
        "Voodoo5": "Vintage Parts & Accessories",
        "Voodoo Banshee": "Vintage Parts & Accessories",
        "Voodoo Rush": "Vintage Parts & Accessories",
        "Quantum3D": "Vintage Parts & Accessories",
        "Raven": "Vintage Parts & Accessories",
        "Obsidian": "Vintage Parts & Accessories",
    },
    "ATI": {
        "Rage": "Vintage Parts & Accessories",
        "Rage Pro": "Vintage Parts & Accessories", 
        "Rage 128": "Vintage Parts & Accessories",
        "Rage Fury": "Vintage Parts & Accessories",
        "Mach": "Vintage Parts & Accessories",
        "All-in-Wonder": "Vintage Parts & Accessories",
        "Radeon 7000": "Vintage Parts & Accessories",
        "Radeon 7200": "Vintage Parts & Accessories",
        "Radeon 7500": "Vintage Parts & Accessories",
        "Radeon 8500": "Vintage Parts & Accessories",
        "Radeon 9000": "Vintage Parts & Accessories",
        "Radeon 9200": "Vintage Parts & Accessories",
        "Radeon 9500": "Vintage Parts & Accessories",
        "Radeon 9600": "Vintage Parts & Accessories",
        "Radeon 9700": "Vintage Parts & Accessories",
        "Radeon 9800": "Vintage Parts & Accessories",
    },
    "Matrox": {
        "Millennium": "Vintage Parts & Accessories",
        "Mystique": "Vintage Parts & Accessories",
        "G200": "Vintage Parts & Accessories", 
        "G400": "Vintage Parts & Accessories",
        "G450": "Vintage Parts & Accessories",
        "G550": "Vintage Parts & Accessories",
        "Parhelia": "Vintage Parts & Accessories",
    },
    "S3": {
        "Savage": "Vintage Parts & Accessories",
        "Savage3D": "Vintage Parts & Accessories",
        "Savage4": "Vintage Parts & Accessories",
        "Savage2000": "Vintage Parts & Accessories",
        "Trio": "Vintage Parts & Accessories",
        "Trio64": "Vintage Parts & Accessories",
        "ViRGE": "Vintage Parts & Accessories",
        "ProSavage": "Vintage Parts & Accessories",
    },
    "Diamond": {
        "Stealth": "Vintage Parts & Accessories",
        "Monster": "Vintage Parts & Accessories",
        "SpeedStar": "Vintage Parts & Accessories",
        "Viper": "Vintage Parts & Accessories",
    },
    "Creative": {
        "3D Blaster": "Vintage Parts & Accessories",
        "Graphics Blaster": "Vintage Parts & Accessories",
        "Annihilator": "Vintage Parts & Accessories",
    },
    "SK hynix": {
        "HMT": "Server Memory (RAM)",
        "HMA": "Server Memory (RAM)", 
        "PC3": "Server Memory (RAM)",
        "PC4": "Server Memory (RAM)",
        "DDR3": "Server Memory (RAM)",
        "DDR4": "Server Memory (RAM)",
        "DDR5": "Server Memory (RAM)",
    },
    "Intel": {
        "Xeon": "Server CPUs/Processors",
        "Xeon Phi": "Server CPUs/Processors",
    }
}